"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersRepository = exports.PostsRepository = exports.PostLikesRepository = exports.PostCommentsRepository = exports.PostAttachmentsRepository = exports.NotificationsRepository = exports.FriendshipsRepository = exports.ConversationsRepository = exports.ConversationMessagesRepository = void 0;
var ConversationMessagesRepository_1 = require("./ConversationMessagesRepository");
Object.defineProperty(exports, "ConversationMessagesRepository", { enumerable: true, get: function () { return ConversationMessagesRepository_1.ConversationMessagesRepository; } });
var ConversationsRepository_1 = require("./ConversationsRepository");
Object.defineProperty(exports, "ConversationsRepository", { enumerable: true, get: function () { return ConversationsRepository_1.ConversationsRepository; } });
var FriendshipsRepository_1 = require("./FriendshipsRepository");
Object.defineProperty(exports, "FriendshipsRepository", { enumerable: true, get: function () { return FriendshipsRepository_1.FriendshipsRepository; } });
var NotificationsRepository_1 = require("./NotificationsRepository");
Object.defineProperty(exports, "NotificationsRepository", { enumerable: true, get: function () { return NotificationsRepository_1.NotificationsRepository; } });
var PostAttachmentsRepository_1 = require("./PostAttachmentsRepository");
Object.defineProperty(exports, "PostAttachmentsRepository", { enumerable: true, get: function () { return PostAttachmentsRepository_1.PostAttachmentsRepository; } });
var PostCommentsRepository_1 = require("./PostCommentsRepository");
Object.defineProperty(exports, "PostCommentsRepository", { enumerable: true, get: function () { return PostCommentsRepository_1.PostCommentsRepository; } });
var PostLikesRepository_1 = require("./PostLikesRepository");
Object.defineProperty(exports, "PostLikesRepository", { enumerable: true, get: function () { return PostLikesRepository_1.PostLikesRepository; } });
var PostsRepository_1 = require("./PostsRepository");
Object.defineProperty(exports, "PostsRepository", { enumerable: true, get: function () { return PostsRepository_1.PostsRepository; } });
var UsersRepository_1 = require("./UsersRepository");
Object.defineProperty(exports, "UsersRepository", { enumerable: true, get: function () { return UsersRepository_1.UsersRepository; } });
